# Site settings
title: Miguel Restrepo
description: Engineer with a background in aerospace, exploring data science and technology through hands-on learning and personal projects.
theme: jekyll-theme-minimal

# Contact / Social
github_username: miguelRepo
email: restrepo.miguel@outlook.com

# UI settings for jekyll-theme-minimal
show_downloads: false
# logo: /assets/profile.png   # Optional: only if you add a profile image

# Build settings
markdown: kramdown
permalink: pretty
