# Site settings
title: Miguel Restrepo
description: Aeronautical engineer exploring data, technology, and software development.
theme: jekyll-theme-minimal

# Contact / Social
github_username: miguelRepo
email: restrepo.miguel@outlook.com

# UI settings for jekyll-theme-minimal
show_downloads: false
# logo: /assets/profile.png   # Optional: only if you add a profile image

# Build settings
markdown: kramdown
permalink: pretty
